language: node_js
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm start
